### ISSUE TITLE
MultiMonteCarlo crashes

### ISSUE THREAD

**Issue by transfluxus** [brightway-lca/bw_processing#48]
Hi,

I have following code to try to run a MultiMonteCarlo

```
import bw2data as bd
from bw2calc import LCA
from bw2calc.monte_carlo import MultiMonteCarlo

bd.projects.set_current("ecoinvent_391") 
ei = bd.Database("ecoinvent_391_cutoff")


act = ei.get_node('a8fe0b37705fe611fac8004ca6cb1afd')
act2 = ei.get_node('413bc4617794c6e8b07038dbeca64adb')

method = ('CML v4.8 2016', 'climate change', 'global warming potential (GWP100)')

demands = [{act: 1,
            act2: 10}]

mc = MultiMonteCarlo(demands, method=method)
mc.calculate()
```

But it crashes with this trace

```
Traceback (most recent call last):
  File ".../bw2calc/monte_carlo.py", line 217, in calculate
    results = pool.map(
              ^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 205, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_thread.RLock' object
```

I am not sure if I am supposed to run it differently- MultiLCA does not take the `use_distributions` and even trying to copy and change the MultiLCA code to include it, does seem to run a normal LCI.

I also tried it with python3.9 but get the same error. The error occurs on Windows and Linux.
I guess is that 
Any help is highly appreciated :)

**Comment by transfluxus** [comment]
I had some "partial" success by changing the
